po/el.po
=> Greek translation full update 17/7/2016

src/ImageManager.py
Also tidied up so GML-tagged comments from the past.
=> Display ofgwrite errors and also send them to any debug log.

src/ImageManager.py
Part 2 of 2. (Part 1 in MBRestart)
try to resolve issues from users corrupting the system!
=> Multiboot - handle corrupted /boot

src/ImageManager.py
Update ImageManager for osmio4k
=> multiboot/backup image - add osmio4k

src/ImageManager.py
Users are restoring backup settings from other receivers which means that the fstab is replaced and contains invalid information for multiboot receivers where fstab contains the boot partition - and leads to crashes or other issues.
This change plus a separate MBrestart change removes the dependency by mounting the boot partition directly before changing STARTUP files (in boot)
=> ImageManager - mount boot partition directly

src/ImageManager.py
... ImageManager - for Zgemma exclude Image backup from main screen until we have fix for Image restore.
.. . insert code to flash specifically for the H9 and also cleanup Image backup files (hopefully for later fix)
=> Zgemma H9 - ignore ImageBackup in ImageManger for the moment

src/MountManager.py
handle zgemma i55plus as per h9
=> zgemma i55plus add mountable SDcard to list

src/ImageManager.py
ImageManager support changes for the growing list of receivers that use a different partition format to build image and then backup the emc image partitions and HiSilicon partitions- again differently.
Needs the complementary Pull on ViX (SystemInfo)
This is a big revamp - have tested on h9, h9Combo, sf8008 and Giga4K's but may have missed something - again h7 needs someone to test as major changes here - thank you again zgemma!
=> ImageManager - changes to flash & backup for zgemma receivers

src/ImageManager.py
oops - deleted batch execution command - put back.
=> ImageManager fix h7 execute batch commands

src/ImageManager.py
recognise move to ViX Release 5.3"
=> ImageManager - ViX now Rel 5.3

src/BackupManager.py, src/H9SDmanager.py, src/IPKInstaller.py, src/ImageManager.py, src/MountManager.py, src/SoftcamManager.py, src/SwapManager.py, src/ui.py
=> Revert "Remove superfluous usage of skin_default in image paths, don't hardco…"

src/ImageManager.py
on initial setup show images in download library
=> ImageManager - restore initial refresh of download image library

src/BackupManager.py, src/ImageManager.py, src/MountManager.py, src/Multibootmgr.py
Changes to ViX-core plugin to support backup and flashing of multiboot images with new multiboot routines.
Changes to   
ImageManager, BackupManager, MountManager, MultibootMgr
=> Multiboot rebuild- Part 2(Part1 in ViX enigma)

src/ImageManager.py, src/MountManager.py
1. MountManager - replace duplicated code in the 2 main routines with a callable routine - saves 125+ lines of code, and simplifies the process as well as future maintenance
2. MountManager - ensure all files are closed.
3. ImageManager - ensure all files are closed
=> Changes to ImageManager & MountManager

src/ImageManager.py
1. PEP8 changes
2. On Image downloads - now provide range of release images by version for OpenViX
3. On ImageDownload - OpenATV & OpenPli now use json on downloads
4. sf8008 (and similar receivers)  provide flashing support for both old & new partition formats
=> ImageManager - updates

src/ImageManager.py
file open was incorrect for specifically h9/i55 image backups
=> ImageManager - fix h9/i55 image backup

src/SoftcamManager.py
bad indented statement impacts status in python3
=> SoftCamManager - fix python 3 status display

src/SoftcamManager.py
After this pull request
https://github.com/OpenViX/enigma2/pull/689
=> [SoftCam] Add Support For Ncam

src/MountManager.py
fixed ability to change hdd device through red button (use as HDD) code.
=> MountManager - solve missing  - use as HDD

po/fi.po
Added "Homebuild URL" and its description.
=> Updated finnish translation

po/fi.po
Added Image Manager Info translations.
=> Updated ViX finnish translation
